// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: my.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Protocol {

  /// <summary>Holder for reflection information generated from my.proto</summary>
  public static partial class MyReflection {

    #region Descriptor
    /// <summary>File descriptor for my.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CghteS5wcm90bxIMb3JnLnByb3RvY29sItYCCgdSZXF1ZXN0Ei4KC3JlcXVl",
            "c3RUeXBlGAEgASgOMhkub3JnLnByb3RvY29sLlJlcXVlc3RUeXBlEhAKCHVz",
            "ZXJuYW1lGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJEiIKBWFnZW50GAQgASgL",
            "MhMub3JnLnByb3RvY29sLkFnZW50EiYKB2Jvb2tpbmcYBSABKAsyFS5vcmcu",
            "cHJvdG9jb2wuQm9va2luZxIkCgZmbGlnaHQYBiABKAsyFC5vcmcucHJvdG9j",
            "b2wuRmxpZ2h0EhIKCnBhc3NlbmdlcnMYByADKAkSFQoNbnVtYmVyT2ZTZWF0",
            "cxgIIAEoBRITCgtkZXN0aW5hdGlvbhgJIAEoCRIVCg1kZXBhcnR1cmVEYXRl",
            "GAogASgJEhEKCXN0YXJ0VGltZRgLIAEoCRIPCgdlbmRUaW1lGAwgASgJEgoK",
            "AmlkGA0gASgDIpQCCghSZXNwb25zZRIwCgxyZXNwb25zZVR5cGUYASABKA4y",
            "Gi5vcmcucHJvdG9jb2wuUmVzcG9uc2VUeXBlEhQKDGVycm9yTWVzc2FnZRgC",
            "IAEoCRIiCgVhZ2VudBgDIAEoCzITLm9yZy5wcm90b2NvbC5BZ2VudBImCgdi",
            "b29raW5nGAQgASgLMhUub3JnLnByb3RvY29sLkJvb2tpbmcSJQoHZmxpZ2h0",
            "cxgFIAMoCzIULm9yZy5wcm90b2NvbC5GbGlnaHQSJwoIYm9va2luZ3MYBiAD",
            "KAsyFS5vcmcucHJvdG9jb2wuQm9va2luZxIkCgZmbGlnaHQYByABKAsyFC5v",
            "cmcucHJvdG9jb2wuRmxpZ2h0IjMKBUFnZW50EgoKAmlkGAEgASgDEgwKBG5h",
            "bWUYAiABKAkSEAoIcGFzc3dvcmQYAyABKAkiZgoHQm9va2luZxIKCgJpZBgB",
            "IAEoAxIkCgZmbGlnaHQYAiABKAsyFC5vcmcucHJvdG9jb2wuRmxpZ2h0EhIK",
            "CnBhc3NlbmdlcnMYAyADKAkSFQoNbnVtYmVyT2ZTZWF0cxgEIAEoBSJtCgZG",
            "bGlnaHQSCgoCaWQYASABKAMSEwoLZGVzdGluYXRpb24YAiABKAkSGQoRZGVw",
            "YXJ0dXJlRGF0ZVRpbWUYAyABKAkSDwoHYWlycG9ydBgEIAEoCRIWCg5hdmFp",
            "bGFibGVTZWF0cxgFIAEoBSqbAQoLUmVxdWVzdFR5cGUSEQoNUkVRVUVTVF9M",
            "T0dJThAAEhIKDlJFUVVFU1RfTE9HT1VUEAESGwoXUkVRVUVTVF9HRVRfQUxM",
            "X0ZMSUdIVFMQAhIvCitSRVFVRVNUX0dFVF9GTElHSFRTX0JZX0RFU1RJTkFU",
            "SU9OX0FORF9EQVRFEAMSFwoTUkVRVUVTVF9CVVlfVElDS0VUUxAEKuQBCgxS",
            "ZXNwb25zZVR5cGUSDwoLUkVTUE9OU0VfT0sQABISCg5SRVNQT05TRV9FUlJP",
            "UhABEhIKDlJFU1BPTlNFX0xPR0lOEAISEwoPUkVTUE9OU0VfTE9HT1VUEAMS",
            "HAoYUkVTUE9OU0VfR0VUX0FMTF9GTElHSFRTEAQSMAosUkVTUE9OU0VfR0VU",
            "X0ZMSUdIVFNfQllfREVTVElOQVRJT05fQU5EX0RBVEUQBRIYChRSRVNQT05T",
            "RV9CVVlfVElDS0VUUxAGEhwKGFJFU1BPTlNFX01PRElGSUVEX0ZMSUdIVBAH",
            "Qg+qAgxPcmcuUHJvdG9jb2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Org.Protocol.RequestType), typeof(global::Org.Protocol.ResponseType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Protocol.Request), global::Org.Protocol.Request.Parser, new[]{ "RequestType", "Username", "Password", "Agent", "Booking", "Flight", "Passengers", "NumberOfSeats", "Destination", "DepartureDate", "StartTime", "EndTime", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Protocol.Response), global::Org.Protocol.Response.Parser, new[]{ "ResponseType", "ErrorMessage", "Agent", "Booking", "Flights", "Bookings", "Flight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Protocol.Agent), global::Org.Protocol.Agent.Parser, new[]{ "Id", "Name", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Protocol.Booking), global::Org.Protocol.Booking.Parser, new[]{ "Id", "Flight", "Passengers", "NumberOfSeats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Protocol.Flight), global::Org.Protocol.Flight.Parser, new[]{ "Id", "Destination", "DepartureDateTime", "Airport", "AvailableSeats" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Enum pentru tipurile de cereri (RequestType)
  /// </summary>
  public enum RequestType {
    [pbr::OriginalName("REQUEST_LOGIN")] RequestLogin = 0,
    [pbr::OriginalName("REQUEST_LOGOUT")] RequestLogout = 1,
    [pbr::OriginalName("REQUEST_GET_ALL_FLIGHTS")] RequestGetAllFlights = 2,
    [pbr::OriginalName("REQUEST_GET_FLIGHTS_BY_DESTINATION_AND_DATE")] RequestGetFlightsByDestinationAndDate = 3,
    [pbr::OriginalName("REQUEST_BUY_TICKETS")] RequestBuyTickets = 4,
  }

  /// <summary>
  /// Enum pentru tipurile de răspunsuri (ResponseType)
  /// </summary>
  public enum ResponseType {
    [pbr::OriginalName("RESPONSE_OK")] ResponseOk = 0,
    [pbr::OriginalName("RESPONSE_ERROR")] ResponseError = 1,
    [pbr::OriginalName("RESPONSE_LOGIN")] ResponseLogin = 2,
    [pbr::OriginalName("RESPONSE_LOGOUT")] ResponseLogout = 3,
    [pbr::OriginalName("RESPONSE_GET_ALL_FLIGHTS")] ResponseGetAllFlights = 4,
    [pbr::OriginalName("RESPONSE_GET_FLIGHTS_BY_DESTINATION_AND_DATE")] ResponseGetFlightsByDestinationAndDate = 5,
    [pbr::OriginalName("RESPONSE_BUY_TICKETS")] ResponseBuyTickets = 6,
    [pbr::OriginalName("RESPONSE_MODIFIED_FLIGHT")] ResponseModifiedFlight = 7,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Mesaj pentru Request
  /// </summary>
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Protocol.MyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      requestType_ = other.requestType_;
      username_ = other.username_;
      password_ = other.password_;
      agent_ = other.agent_ != null ? other.agent_.Clone() : null;
      booking_ = other.booking_ != null ? other.booking_.Clone() : null;
      flight_ = other.flight_ != null ? other.flight_.Clone() : null;
      passengers_ = other.passengers_.Clone();
      numberOfSeats_ = other.numberOfSeats_;
      destination_ = other.destination_;
      departureDate_ = other.departureDate_;
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "requestType" field.</summary>
    public const int RequestTypeFieldNumber = 1;
    private global::Org.Protocol.RequestType requestType_ = global::Org.Protocol.RequestType.RequestLogin;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.RequestType RequestType {
      get { return requestType_; }
      set {
        requestType_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    /// <summary>
    /// Pentru LOGIN
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    /// <summary>
    /// Pentru LOGIN
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "agent" field.</summary>
    public const int AgentFieldNumber = 4;
    private global::Org.Protocol.Agent agent_;
    /// <summary>
    /// Pentru LOGOUT
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.Agent Agent {
      get { return agent_; }
      set {
        agent_ = value;
      }
    }

    /// <summary>Field number for the "booking" field.</summary>
    public const int BookingFieldNumber = 5;
    private global::Org.Protocol.Booking booking_;
    /// <summary>
    /// Pentru BUY_TICKETS
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.Booking Booking {
      get { return booking_; }
      set {
        booking_ = value;
      }
    }

    /// <summary>Field number for the "flight" field.</summary>
    public const int FlightFieldNumber = 6;
    private global::Org.Protocol.Flight flight_;
    /// <summary>
    /// Pentru BUY_TICKETS sau modificare de zbor
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.Flight Flight {
      get { return flight_; }
      set {
        flight_ = value;
      }
    }

    /// <summary>Field number for the "passengers" field.</summary>
    public const int PassengersFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_passengers_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> passengers_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Lista pasagerilor pentru BUY_TICKETS
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Passengers {
      get { return passengers_; }
    }

    /// <summary>Field number for the "numberOfSeats" field.</summary>
    public const int NumberOfSeatsFieldNumber = 8;
    private int numberOfSeats_;
    /// <summary>
    /// Numărul de locuri pentru BUY_TICKETS
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumberOfSeats {
      get { return numberOfSeats_; }
      set {
        numberOfSeats_ = value;
      }
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 9;
    private string destination_ = "";
    /// <summary>
    /// Pentru GET_FLIGHTS_BY_DESTINATION_AND_DATE
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "departureDate" field.</summary>
    public const int DepartureDateFieldNumber = 10;
    private string departureDate_ = "";
    /// <summary>
    /// Data plecării (ISO 8601)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DepartureDate {
      get { return departureDate_; }
      set {
        departureDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "startTime" field.</summary>
    public const int StartTimeFieldNumber = 11;
    private string startTime_ = "";
    /// <summary>
    /// Ora de start (ISO 8601)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StartTime {
      get { return startTime_; }
      set {
        startTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endTime" field.</summary>
    public const int EndTimeFieldNumber = 12;
    private string endTime_ = "";
    /// <summary>
    /// Ora de sfârșit (ISO 8601)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EndTime {
      get { return endTime_; }
      set {
        endTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 13;
    private long id_;
    /// <summary>
    /// ID pentru identificare
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestType != other.RequestType) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (!object.Equals(Agent, other.Agent)) return false;
      if (!object.Equals(Booking, other.Booking)) return false;
      if (!object.Equals(Flight, other.Flight)) return false;
      if(!passengers_.Equals(other.passengers_)) return false;
      if (NumberOfSeats != other.NumberOfSeats) return false;
      if (Destination != other.Destination) return false;
      if (DepartureDate != other.DepartureDate) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestType != global::Org.Protocol.RequestType.RequestLogin) hash ^= RequestType.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (agent_ != null) hash ^= Agent.GetHashCode();
      if (booking_ != null) hash ^= Booking.GetHashCode();
      if (flight_ != null) hash ^= Flight.GetHashCode();
      hash ^= passengers_.GetHashCode();
      if (NumberOfSeats != 0) hash ^= NumberOfSeats.GetHashCode();
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (DepartureDate.Length != 0) hash ^= DepartureDate.GetHashCode();
      if (StartTime.Length != 0) hash ^= StartTime.GetHashCode();
      if (EndTime.Length != 0) hash ^= EndTime.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestType != global::Org.Protocol.RequestType.RequestLogin) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RequestType);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (agent_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Agent);
      }
      if (booking_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Booking);
      }
      if (flight_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Flight);
      }
      passengers_.WriteTo(output, _repeated_passengers_codec);
      if (NumberOfSeats != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(NumberOfSeats);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Destination);
      }
      if (DepartureDate.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(DepartureDate);
      }
      if (StartTime.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(StartTime);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(EndTime);
      }
      if (Id != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestType != global::Org.Protocol.RequestType.RequestLogin) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RequestType);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (agent_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Agent);
      }
      if (booking_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Booking);
      }
      if (flight_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Flight);
      }
      passengers_.WriteTo(ref output, _repeated_passengers_codec);
      if (NumberOfSeats != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(NumberOfSeats);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Destination);
      }
      if (DepartureDate.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(DepartureDate);
      }
      if (StartTime.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(StartTime);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(EndTime);
      }
      if (Id != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RequestType != global::Org.Protocol.RequestType.RequestLogin) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestType);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (agent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Agent);
      }
      if (booking_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Booking);
      }
      if (flight_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Flight);
      }
      size += passengers_.CalculateSize(_repeated_passengers_codec);
      if (NumberOfSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfSeats);
      }
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (DepartureDate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DepartureDate);
      }
      if (StartTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartTime);
      }
      if (EndTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndTime);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.RequestType != global::Org.Protocol.RequestType.RequestLogin) {
        RequestType = other.RequestType;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.agent_ != null) {
        if (agent_ == null) {
          Agent = new global::Org.Protocol.Agent();
        }
        Agent.MergeFrom(other.Agent);
      }
      if (other.booking_ != null) {
        if (booking_ == null) {
          Booking = new global::Org.Protocol.Booking();
        }
        Booking.MergeFrom(other.Booking);
      }
      if (other.flight_ != null) {
        if (flight_ == null) {
          Flight = new global::Org.Protocol.Flight();
        }
        Flight.MergeFrom(other.Flight);
      }
      passengers_.Add(other.passengers_);
      if (other.NumberOfSeats != 0) {
        NumberOfSeats = other.NumberOfSeats;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.DepartureDate.Length != 0) {
        DepartureDate = other.DepartureDate;
      }
      if (other.StartTime.Length != 0) {
        StartTime = other.StartTime;
      }
      if (other.EndTime.Length != 0) {
        EndTime = other.EndTime;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestType = (global::Org.Protocol.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 34: {
            if (agent_ == null) {
              Agent = new global::Org.Protocol.Agent();
            }
            input.ReadMessage(Agent);
            break;
          }
          case 42: {
            if (booking_ == null) {
              Booking = new global::Org.Protocol.Booking();
            }
            input.ReadMessage(Booking);
            break;
          }
          case 50: {
            if (flight_ == null) {
              Flight = new global::Org.Protocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
          case 58: {
            passengers_.AddEntriesFrom(input, _repeated_passengers_codec);
            break;
          }
          case 64: {
            NumberOfSeats = input.ReadInt32();
            break;
          }
          case 74: {
            Destination = input.ReadString();
            break;
          }
          case 82: {
            DepartureDate = input.ReadString();
            break;
          }
          case 90: {
            StartTime = input.ReadString();
            break;
          }
          case 98: {
            EndTime = input.ReadString();
            break;
          }
          case 104: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RequestType = (global::Org.Protocol.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 34: {
            if (agent_ == null) {
              Agent = new global::Org.Protocol.Agent();
            }
            input.ReadMessage(Agent);
            break;
          }
          case 42: {
            if (booking_ == null) {
              Booking = new global::Org.Protocol.Booking();
            }
            input.ReadMessage(Booking);
            break;
          }
          case 50: {
            if (flight_ == null) {
              Flight = new global::Org.Protocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
          case 58: {
            passengers_.AddEntriesFrom(ref input, _repeated_passengers_codec);
            break;
          }
          case 64: {
            NumberOfSeats = input.ReadInt32();
            break;
          }
          case 74: {
            Destination = input.ReadString();
            break;
          }
          case 82: {
            DepartureDate = input.ReadString();
            break;
          }
          case 90: {
            StartTime = input.ReadString();
            break;
          }
          case 98: {
            EndTime = input.ReadString();
            break;
          }
          case 104: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Mesaj pentru Response
  /// </summary>
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Protocol.MyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      responseType_ = other.responseType_;
      errorMessage_ = other.errorMessage_;
      agent_ = other.agent_ != null ? other.agent_.Clone() : null;
      booking_ = other.booking_ != null ? other.booking_.Clone() : null;
      flights_ = other.flights_.Clone();
      bookings_ = other.bookings_.Clone();
      flight_ = other.flight_ != null ? other.flight_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "responseType" field.</summary>
    public const int ResponseTypeFieldNumber = 1;
    private global::Org.Protocol.ResponseType responseType_ = global::Org.Protocol.ResponseType.ResponseOk;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.ResponseType ResponseType {
      get { return responseType_; }
      set {
        responseType_ = value;
      }
    }

    /// <summary>Field number for the "errorMessage" field.</summary>
    public const int ErrorMessageFieldNumber = 2;
    private string errorMessage_ = "";
    /// <summary>
    /// Mesaj de eroare, dacă există
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "agent" field.</summary>
    public const int AgentFieldNumber = 3;
    private global::Org.Protocol.Agent agent_;
    /// <summary>
    /// Răspuns pentru LOGIN/LOGOUT
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.Agent Agent {
      get { return agent_; }
      set {
        agent_ = value;
      }
    }

    /// <summary>Field number for the "booking" field.</summary>
    public const int BookingFieldNumber = 4;
    private global::Org.Protocol.Booking booking_;
    /// <summary>
    /// Răspuns pentru BUY_TICKETS
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.Booking Booking {
      get { return booking_; }
      set {
        booking_ = value;
      }
    }

    /// <summary>Field number for the "flights" field.</summary>
    public const int FlightsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Org.Protocol.Flight> _repeated_flights_codec
        = pb::FieldCodec.ForMessage(42, global::Org.Protocol.Flight.Parser);
    private readonly pbc::RepeatedField<global::Org.Protocol.Flight> flights_ = new pbc::RepeatedField<global::Org.Protocol.Flight>();
    /// <summary>
    /// Răspuns pentru GET_ALL_FLIGHTS sau GET_FLIGHTS_BY_DESTINATION_AND_DATE
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Protocol.Flight> Flights {
      get { return flights_; }
    }

    /// <summary>Field number for the "bookings" field.</summary>
    public const int BookingsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Org.Protocol.Booking> _repeated_bookings_codec
        = pb::FieldCodec.ForMessage(50, global::Org.Protocol.Booking.Parser);
    private readonly pbc::RepeatedField<global::Org.Protocol.Booking> bookings_ = new pbc::RepeatedField<global::Org.Protocol.Booking>();
    /// <summary>
    /// Răspuns pentru rezervări multiple
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Protocol.Booking> Bookings {
      get { return bookings_; }
    }

    /// <summary>Field number for the "flight" field.</summary>
    public const int FlightFieldNumber = 7;
    private global::Org.Protocol.Flight flight_;
    /// <summary>
    /// Răspuns pentru un zbor modificat
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.Flight Flight {
      get { return flight_; }
      set {
        flight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseType != other.ResponseType) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      if (!object.Equals(Agent, other.Agent)) return false;
      if (!object.Equals(Booking, other.Booking)) return false;
      if(!flights_.Equals(other.flights_)) return false;
      if(!bookings_.Equals(other.bookings_)) return false;
      if (!object.Equals(Flight, other.Flight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseType != global::Org.Protocol.ResponseType.ResponseOk) hash ^= ResponseType.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (agent_ != null) hash ^= Agent.GetHashCode();
      if (booking_ != null) hash ^= Booking.GetHashCode();
      hash ^= flights_.GetHashCode();
      hash ^= bookings_.GetHashCode();
      if (flight_ != null) hash ^= Flight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResponseType != global::Org.Protocol.ResponseType.ResponseOk) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ResponseType);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage);
      }
      if (agent_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Agent);
      }
      if (booking_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Booking);
      }
      flights_.WriteTo(output, _repeated_flights_codec);
      bookings_.WriteTo(output, _repeated_bookings_codec);
      if (flight_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Flight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResponseType != global::Org.Protocol.ResponseType.ResponseOk) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ResponseType);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage);
      }
      if (agent_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Agent);
      }
      if (booking_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Booking);
      }
      flights_.WriteTo(ref output, _repeated_flights_codec);
      bookings_.WriteTo(ref output, _repeated_bookings_codec);
      if (flight_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Flight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResponseType != global::Org.Protocol.ResponseType.ResponseOk) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseType);
      }
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (agent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Agent);
      }
      if (booking_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Booking);
      }
      size += flights_.CalculateSize(_repeated_flights_codec);
      size += bookings_.CalculateSize(_repeated_bookings_codec);
      if (flight_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Flight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.ResponseType != global::Org.Protocol.ResponseType.ResponseOk) {
        ResponseType = other.ResponseType;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      if (other.agent_ != null) {
        if (agent_ == null) {
          Agent = new global::Org.Protocol.Agent();
        }
        Agent.MergeFrom(other.Agent);
      }
      if (other.booking_ != null) {
        if (booking_ == null) {
          Booking = new global::Org.Protocol.Booking();
        }
        Booking.MergeFrom(other.Booking);
      }
      flights_.Add(other.flights_);
      bookings_.Add(other.bookings_);
      if (other.flight_ != null) {
        if (flight_ == null) {
          Flight = new global::Org.Protocol.Flight();
        }
        Flight.MergeFrom(other.Flight);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResponseType = (global::Org.Protocol.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 26: {
            if (agent_ == null) {
              Agent = new global::Org.Protocol.Agent();
            }
            input.ReadMessage(Agent);
            break;
          }
          case 34: {
            if (booking_ == null) {
              Booking = new global::Org.Protocol.Booking();
            }
            input.ReadMessage(Booking);
            break;
          }
          case 42: {
            flights_.AddEntriesFrom(input, _repeated_flights_codec);
            break;
          }
          case 50: {
            bookings_.AddEntriesFrom(input, _repeated_bookings_codec);
            break;
          }
          case 58: {
            if (flight_ == null) {
              Flight = new global::Org.Protocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResponseType = (global::Org.Protocol.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 26: {
            if (agent_ == null) {
              Agent = new global::Org.Protocol.Agent();
            }
            input.ReadMessage(Agent);
            break;
          }
          case 34: {
            if (booking_ == null) {
              Booking = new global::Org.Protocol.Booking();
            }
            input.ReadMessage(Booking);
            break;
          }
          case 42: {
            flights_.AddEntriesFrom(ref input, _repeated_flights_codec);
            break;
          }
          case 50: {
            bookings_.AddEntriesFrom(ref input, _repeated_bookings_codec);
            break;
          }
          case 58: {
            if (flight_ == null) {
              Flight = new global::Org.Protocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Mesaj pentru Agent
  /// </summary>
  public sealed partial class Agent : pb::IMessage<Agent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Agent> _parser = new pb::MessageParser<Agent>(() => new Agent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Agent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Protocol.MyReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Agent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Agent(Agent other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Agent Clone() {
      return new Agent(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// ID-ul agentului
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    /// Numele agentului
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    /// <summary>
    /// Parola agentului
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Agent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Agent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Agent other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Mesaj pentru Booking
  /// </summary>
  public sealed partial class Booking : pb::IMessage<Booking>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Booking> _parser = new pb::MessageParser<Booking>(() => new Booking());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Booking> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Protocol.MyReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Booking() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Booking(Booking other) : this() {
      id_ = other.id_;
      flight_ = other.flight_ != null ? other.flight_.Clone() : null;
      passengers_ = other.passengers_.Clone();
      numberOfSeats_ = other.numberOfSeats_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Booking Clone() {
      return new Booking(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// ID-ul rezervării
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "flight" field.</summary>
    public const int FlightFieldNumber = 2;
    private global::Org.Protocol.Flight flight_;
    /// <summary>
    /// Zborul asociat
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Protocol.Flight Flight {
      get { return flight_; }
      set {
        flight_ = value;
      }
    }

    /// <summary>Field number for the "passengers" field.</summary>
    public const int PassengersFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_passengers_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> passengers_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Lista pasagerilor
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Passengers {
      get { return passengers_; }
    }

    /// <summary>Field number for the "numberOfSeats" field.</summary>
    public const int NumberOfSeatsFieldNumber = 4;
    private int numberOfSeats_;
    /// <summary>
    /// Numărul de locuri rezervate
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumberOfSeats {
      get { return numberOfSeats_; }
      set {
        numberOfSeats_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Booking);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Booking other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Flight, other.Flight)) return false;
      if(!passengers_.Equals(other.passengers_)) return false;
      if (NumberOfSeats != other.NumberOfSeats) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (flight_ != null) hash ^= Flight.GetHashCode();
      hash ^= passengers_.GetHashCode();
      if (NumberOfSeats != 0) hash ^= NumberOfSeats.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (flight_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Flight);
      }
      passengers_.WriteTo(output, _repeated_passengers_codec);
      if (NumberOfSeats != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumberOfSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (flight_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Flight);
      }
      passengers_.WriteTo(ref output, _repeated_passengers_codec);
      if (NumberOfSeats != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumberOfSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (flight_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Flight);
      }
      size += passengers_.CalculateSize(_repeated_passengers_codec);
      if (NumberOfSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfSeats);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Booking other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.flight_ != null) {
        if (flight_ == null) {
          Flight = new global::Org.Protocol.Flight();
        }
        Flight.MergeFrom(other.Flight);
      }
      passengers_.Add(other.passengers_);
      if (other.NumberOfSeats != 0) {
        NumberOfSeats = other.NumberOfSeats;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (flight_ == null) {
              Flight = new global::Org.Protocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
          case 26: {
            passengers_.AddEntriesFrom(input, _repeated_passengers_codec);
            break;
          }
          case 32: {
            NumberOfSeats = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (flight_ == null) {
              Flight = new global::Org.Protocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
          case 26: {
            passengers_.AddEntriesFrom(ref input, _repeated_passengers_codec);
            break;
          }
          case 32: {
            NumberOfSeats = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Mesaj pentru Flight
  /// </summary>
  public sealed partial class Flight : pb::IMessage<Flight>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Flight> _parser = new pb::MessageParser<Flight>(() => new Flight());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Flight> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Protocol.MyReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Flight() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Flight(Flight other) : this() {
      id_ = other.id_;
      destination_ = other.destination_;
      departureDateTime_ = other.departureDateTime_;
      airport_ = other.airport_;
      availableSeats_ = other.availableSeats_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Flight Clone() {
      return new Flight(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// ID-ul zborului
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 2;
    private string destination_ = "";
    /// <summary>
    /// Destinația
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "departureDateTime" field.</summary>
    public const int DepartureDateTimeFieldNumber = 3;
    private string departureDateTime_ = "";
    /// <summary>
    /// Data și ora plecării (ISO 8601)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DepartureDateTime {
      get { return departureDateTime_; }
      set {
        departureDateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "airport" field.</summary>
    public const int AirportFieldNumber = 4;
    private string airport_ = "";
    /// <summary>
    /// Aeroportul
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Airport {
      get { return airport_; }
      set {
        airport_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "availableSeats" field.</summary>
    public const int AvailableSeatsFieldNumber = 5;
    private int availableSeats_;
    /// <summary>
    /// Numărul de locuri disponibile
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvailableSeats {
      get { return availableSeats_; }
      set {
        availableSeats_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Flight);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Flight other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Destination != other.Destination) return false;
      if (DepartureDateTime != other.DepartureDateTime) return false;
      if (Airport != other.Airport) return false;
      if (AvailableSeats != other.AvailableSeats) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (DepartureDateTime.Length != 0) hash ^= DepartureDateTime.GetHashCode();
      if (Airport.Length != 0) hash ^= Airport.GetHashCode();
      if (AvailableSeats != 0) hash ^= AvailableSeats.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Destination);
      }
      if (DepartureDateTime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DepartureDateTime);
      }
      if (Airport.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Airport);
      }
      if (AvailableSeats != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AvailableSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Destination);
      }
      if (DepartureDateTime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DepartureDateTime);
      }
      if (Airport.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Airport);
      }
      if (AvailableSeats != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AvailableSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (DepartureDateTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DepartureDateTime);
      }
      if (Airport.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Airport);
      }
      if (AvailableSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvailableSeats);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Flight other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.DepartureDateTime.Length != 0) {
        DepartureDateTime = other.DepartureDateTime;
      }
      if (other.Airport.Length != 0) {
        Airport = other.Airport;
      }
      if (other.AvailableSeats != 0) {
        AvailableSeats = other.AvailableSeats;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Destination = input.ReadString();
            break;
          }
          case 26: {
            DepartureDateTime = input.ReadString();
            break;
          }
          case 34: {
            Airport = input.ReadString();
            break;
          }
          case 40: {
            AvailableSeats = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Destination = input.ReadString();
            break;
          }
          case 26: {
            DepartureDateTime = input.ReadString();
            break;
          }
          case 34: {
            Airport = input.ReadString();
            break;
          }
          case 40: {
            AvailableSeats = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
